#!/bin/bash -e

function exit_handler() {
    exit_code=$?
    cleanup
    exit $exit_code
}

function usage() {
    echo "$0 -f <config_file> <path> <terraform_command>"
    exit
}

function cleanup() {
    if [ -f "$tmp" ]; then
        for f in $(cat "${tmp}"); do
            rm $f
        done
        rm "${tmp}"
    fi
}

tmp=$(mktemp)

trap "exit_handler" SIGINT SIGTERM EXIT

if [ $# -lt 3 ]; then
    usage
    exit 1
fi

while getopts "f:s:" opt; do
  case ${opt} in
      f) config_file=${OPTARG}
         ;;
      s) secrets_ext=${OPTARG}
         ;;
      *) echo "Invalid option: -${OPTARG}"
         usage
         exit 1
         ;;
  esac
done

if [ ! -f "${config_file}" ];
then
    echo "Config file ${config_file} not found"
    exit 1
else
    shift
    shift
fi

if [ -n "${secrets_ext}" ]; then
    shift
    shift
    ext="$secrets_ext"
    for f in $(find . -name "*$ext" 2>/dev/null); do
        outfile=${f%$ext}
        sops -d "$f" > "$outfile"
        echo $outfile >> $tmp
    done
fi

for f in $(find . -name '*.tf.tpl'); do
    outfile=${f/.tf.tpl/.tf};
    gomplate -d $config_file -f $f > $outfile;
    echo $outfile >> $tmp
done

terraform "$@"

exit 0
